### ISSUE TITLE
Too many lines of code for SVGs

### ISSUE THREAD

**Issue by charlie-quinn** [charlie-quinn/dsn1676-term-project#2]
I've tried simplifying my SVGs in illustrator, svgo-gui, and SVGOMG - but I still end up with a million lines of code. I know that we are supposed to be placing this code in our html file (allowing us to manually tweak and link with CSS/JS), but even with my elements grouped and simplified in Adobe Illustrator, the illustrations are still too complicated to want to read through the code.

@thomasjbradley what do you think I should do?

![screen shot 2015-04-04 at 10 58 34 pm](https://cloud.githubusercontent.com/assets/6362454/6995562/3cee6846-db1e-11e4-910e-4ceb59478ffa.png)
![screen shot 2015-04-04 at 10 45 49 pm](https://cloud.githubusercontent.com/assets/6362454/6995565/47138414-db1e-11e4-8daa-fa8c29a7b9fe.png)

**Comment by thomasjbradley** [comment]
There's not much you can do, the illustrations are really complex.
You could try looking into SVG icons, like I covered in the videos, but I don't know if that will help.
